#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPhoneStore
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ASPNETDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertItem_Info(Item_Info instance);
    partial void UpdateItem_Info(Item_Info instance);
    partial void DeleteItem_Info(Item_Info instance);
    partial void InsertItem_Type_Info(Item_Type_Info instance);
    partial void UpdateItem_Type_Info(Item_Type_Info instance);
    partial void DeleteItem_Type_Info(Item_Type_Info instance);
    partial void InsertManufacturer_Info(Manufacturer_Info instance);
    partial void UpdateManufacturer_Info(Manufacturer_Info instance);
    partial void DeleteManufacturer_Info(Manufacturer_Info instance);
    partial void InsertItem_Storage_Info(Item_Storage_Info instance);
    partial void UpdateItem_Storage_Info(Item_Storage_Info instance);
    partial void DeleteItem_Storage_Info(Item_Storage_Info instance);
    partial void InsertCustomer_Info(Customer_Info instance);
    partial void UpdateCustomer_Info(Customer_Info instance);
    partial void DeleteCustomer_Info(Customer_Info instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ASPNETDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Item_Info> Item_Infos
		{
			get
			{
				return this.GetTable<Item_Info>();
			}
		}
		
		public System.Data.Linq.Table<Item_Type_Info> Item_Type_Infos
		{
			get
			{
				return this.GetTable<Item_Type_Info>();
			}
		}
		
		public System.Data.Linq.Table<Manufacturer_Info> Manufacturer_Infos
		{
			get
			{
				return this.GetTable<Manufacturer_Info>();
			}
		}
		
		public System.Data.Linq.Table<Item_Storage_Info> Item_Storage_Infos
		{
			get
			{
				return this.GetTable<Item_Storage_Info>();
			}
		}
		
		public System.Data.Linq.Table<Customer_Info> Customer_Infos
		{
			get
			{
				return this.GetTable<Customer_Info>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Item_Info")]
	public partial class Item_Info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Item_ID;
		
		private string _Item_Name;
		
		private System.Nullable<long> _Item_Type_ID;
		
		private System.Nullable<double> _Item_Price;
		
		private System.Nullable<long> _Item_Price_Currency_ID;
		
		private System.Nullable<long> _Item_Manufacturer_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnItem_IDChanging(long value);
    partial void OnItem_IDChanged();
    partial void OnItem_NameChanging(string value);
    partial void OnItem_NameChanged();
    partial void OnItem_Type_IDChanging(System.Nullable<long> value);
    partial void OnItem_Type_IDChanged();
    partial void OnItem_PriceChanging(System.Nullable<double> value);
    partial void OnItem_PriceChanged();
    partial void OnItem_Price_Currency_IDChanging(System.Nullable<long> value);
    partial void OnItem_Price_Currency_IDChanged();
    partial void OnItem_Manufacturer_IDChanging(System.Nullable<long> value);
    partial void OnItem_Manufacturer_IDChanged();
    #endregion
		
		public Item_Info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_ID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Item_ID
		{
			get
			{
				return this._Item_ID;
			}
			set
			{
				if ((this._Item_ID != value))
				{
					this.OnItem_IDChanging(value);
					this.SendPropertyChanging();
					this._Item_ID = value;
					this.SendPropertyChanged("Item_ID");
					this.OnItem_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Name", DbType="NVarChar(50)")]
		public string Item_Name
		{
			get
			{
				return this._Item_Name;
			}
			set
			{
				if ((this._Item_Name != value))
				{
					this.OnItem_NameChanging(value);
					this.SendPropertyChanging();
					this._Item_Name = value;
					this.SendPropertyChanged("Item_Name");
					this.OnItem_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Type_ID", DbType="BigInt")]
		public System.Nullable<long> Item_Type_ID
		{
			get
			{
				return this._Item_Type_ID;
			}
			set
			{
				if ((this._Item_Type_ID != value))
				{
					this.OnItem_Type_IDChanging(value);
					this.SendPropertyChanging();
					this._Item_Type_ID = value;
					this.SendPropertyChanged("Item_Type_ID");
					this.OnItem_Type_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Price", DbType="Float")]
		public System.Nullable<double> Item_Price
		{
			get
			{
				return this._Item_Price;
			}
			set
			{
				if ((this._Item_Price != value))
				{
					this.OnItem_PriceChanging(value);
					this.SendPropertyChanging();
					this._Item_Price = value;
					this.SendPropertyChanged("Item_Price");
					this.OnItem_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Price_Currency_ID", DbType="BigInt")]
		public System.Nullable<long> Item_Price_Currency_ID
		{
			get
			{
				return this._Item_Price_Currency_ID;
			}
			set
			{
				if ((this._Item_Price_Currency_ID != value))
				{
					this.OnItem_Price_Currency_IDChanging(value);
					this.SendPropertyChanging();
					this._Item_Price_Currency_ID = value;
					this.SendPropertyChanged("Item_Price_Currency_ID");
					this.OnItem_Price_Currency_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Manufacturer_ID", DbType="BigInt")]
		public System.Nullable<long> Item_Manufacturer_ID
		{
			get
			{
				return this._Item_Manufacturer_ID;
			}
			set
			{
				if ((this._Item_Manufacturer_ID != value))
				{
					this.OnItem_Manufacturer_IDChanging(value);
					this.SendPropertyChanging();
					this._Item_Manufacturer_ID = value;
					this.SendPropertyChanged("Item_Manufacturer_ID");
					this.OnItem_Manufacturer_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Item_Type_Info")]
	public partial class Item_Type_Info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Item_Type_ID;
		
		private string _Item_Type_Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnItem_Type_IDChanging(long value);
    partial void OnItem_Type_IDChanged();
    partial void OnItem_Type_NameChanging(string value);
    partial void OnItem_Type_NameChanged();
    #endregion
		
		public Item_Type_Info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Type_ID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Item_Type_ID
		{
			get
			{
				return this._Item_Type_ID;
			}
			set
			{
				if ((this._Item_Type_ID != value))
				{
					this.OnItem_Type_IDChanging(value);
					this.SendPropertyChanging();
					this._Item_Type_ID = value;
					this.SendPropertyChanged("Item_Type_ID");
					this.OnItem_Type_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Type_Name", DbType="NVarChar(50)")]
		public string Item_Type_Name
		{
			get
			{
				return this._Item_Type_Name;
			}
			set
			{
				if ((this._Item_Type_Name != value))
				{
					this.OnItem_Type_NameChanging(value);
					this.SendPropertyChanging();
					this._Item_Type_Name = value;
					this.SendPropertyChanged("Item_Type_Name");
					this.OnItem_Type_NameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Manufacturer_Info")]
	public partial class Manufacturer_Info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Manufacturer_ID;
		
		private string _Manufacturer_Name;
		
		private string _Manufacturer_Logo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnManufacturer_IDChanging(long value);
    partial void OnManufacturer_IDChanged();
    partial void OnManufacturer_NameChanging(string value);
    partial void OnManufacturer_NameChanged();
    partial void OnManufacturer_LogoChanging(string value);
    partial void OnManufacturer_LogoChanged();
    #endregion
		
		public Manufacturer_Info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manufacturer_ID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Manufacturer_ID
		{
			get
			{
				return this._Manufacturer_ID;
			}
			set
			{
				if ((this._Manufacturer_ID != value))
				{
					this.OnManufacturer_IDChanging(value);
					this.SendPropertyChanging();
					this._Manufacturer_ID = value;
					this.SendPropertyChanged("Manufacturer_ID");
					this.OnManufacturer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manufacturer_Name", DbType="NVarChar(50)")]
		public string Manufacturer_Name
		{
			get
			{
				return this._Manufacturer_Name;
			}
			set
			{
				if ((this._Manufacturer_Name != value))
				{
					this.OnManufacturer_NameChanging(value);
					this.SendPropertyChanging();
					this._Manufacturer_Name = value;
					this.SendPropertyChanged("Manufacturer_Name");
					this.OnManufacturer_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manufacturer_Logo", DbType="NVarChar(MAX)")]
		public string Manufacturer_Logo
		{
			get
			{
				return this._Manufacturer_Logo;
			}
			set
			{
				if ((this._Manufacturer_Logo != value))
				{
					this.OnManufacturer_LogoChanging(value);
					this.SendPropertyChanging();
					this._Manufacturer_Logo = value;
					this.SendPropertyChanged("Manufacturer_Logo");
					this.OnManufacturer_LogoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Item_Storage_Info")]
	public partial class Item_Storage_Info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Item_Serial_Number;
		
		private System.Nullable<long> _Item_ID;
		
		private string _Item_Color;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnItem_Serial_NumberChanging(long value);
    partial void OnItem_Serial_NumberChanged();
    partial void OnItem_IDChanging(System.Nullable<long> value);
    partial void OnItem_IDChanged();
    partial void OnItem_ColorChanging(string value);
    partial void OnItem_ColorChanged();
    #endregion
		
		public Item_Storage_Info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Serial_Number", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Item_Serial_Number
		{
			get
			{
				return this._Item_Serial_Number;
			}
			set
			{
				if ((this._Item_Serial_Number != value))
				{
					this.OnItem_Serial_NumberChanging(value);
					this.SendPropertyChanging();
					this._Item_Serial_Number = value;
					this.SendPropertyChanged("Item_Serial_Number");
					this.OnItem_Serial_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_ID", DbType="BigInt")]
		public System.Nullable<long> Item_ID
		{
			get
			{
				return this._Item_ID;
			}
			set
			{
				if ((this._Item_ID != value))
				{
					this.OnItem_IDChanging(value);
					this.SendPropertyChanging();
					this._Item_ID = value;
					this.SendPropertyChanged("Item_ID");
					this.OnItem_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_Color", DbType="NVarChar(50)")]
		public string Item_Color
		{
			get
			{
				return this._Item_Color;
			}
			set
			{
				if ((this._Item_Color != value))
				{
					this.OnItem_ColorChanging(value);
					this.SendPropertyChanging();
					this._Item_Color = value;
					this.SendPropertyChanged("Item_Color");
					this.OnItem_ColorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer_Info")]
	public partial class Customer_Info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Customer_ID;
		
		private string _Customer_FirstName;
		
		private string _Customer_LastName;
		
		private string _Customer_Address;
		
		private string _Customer_Phone_Number;
		
		private string _Customer_Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomer_IDChanging(long value);
    partial void OnCustomer_IDChanged();
    partial void OnCustomer_FirstNameChanging(string value);
    partial void OnCustomer_FirstNameChanged();
    partial void OnCustomer_LastNameChanging(string value);
    partial void OnCustomer_LastNameChanged();
    partial void OnCustomer_AddressChanging(string value);
    partial void OnCustomer_AddressChanged();
    partial void OnCustomer_Phone_NumberChanging(string value);
    partial void OnCustomer_Phone_NumberChanged();
    partial void OnCustomer_EmailChanging(string value);
    partial void OnCustomer_EmailChanged();
    #endregion
		
		public Customer_Info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Customer_ID
		{
			get
			{
				return this._Customer_ID;
			}
			set
			{
				if ((this._Customer_ID != value))
				{
					this.OnCustomer_IDChanging(value);
					this.SendPropertyChanging();
					this._Customer_ID = value;
					this.SendPropertyChanged("Customer_ID");
					this.OnCustomer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_FirstName", DbType="NVarChar(256)")]
		public string Customer_FirstName
		{
			get
			{
				return this._Customer_FirstName;
			}
			set
			{
				if ((this._Customer_FirstName != value))
				{
					this.OnCustomer_FirstNameChanging(value);
					this.SendPropertyChanging();
					this._Customer_FirstName = value;
					this.SendPropertyChanged("Customer_FirstName");
					this.OnCustomer_FirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_LastName", DbType="NVarChar(256)")]
		public string Customer_LastName
		{
			get
			{
				return this._Customer_LastName;
			}
			set
			{
				if ((this._Customer_LastName != value))
				{
					this.OnCustomer_LastNameChanging(value);
					this.SendPropertyChanging();
					this._Customer_LastName = value;
					this.SendPropertyChanged("Customer_LastName");
					this.OnCustomer_LastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_Address", DbType="NVarChar(256)")]
		public string Customer_Address
		{
			get
			{
				return this._Customer_Address;
			}
			set
			{
				if ((this._Customer_Address != value))
				{
					this.OnCustomer_AddressChanging(value);
					this.SendPropertyChanging();
					this._Customer_Address = value;
					this.SendPropertyChanged("Customer_Address");
					this.OnCustomer_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_Phone_Number", DbType="NVarChar(30)")]
		public string Customer_Phone_Number
		{
			get
			{
				return this._Customer_Phone_Number;
			}
			set
			{
				if ((this._Customer_Phone_Number != value))
				{
					this.OnCustomer_Phone_NumberChanging(value);
					this.SendPropertyChanging();
					this._Customer_Phone_Number = value;
					this.SendPropertyChanged("Customer_Phone_Number");
					this.OnCustomer_Phone_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_Email", DbType="NVarChar(256)")]
		public string Customer_Email
		{
			get
			{
				return this._Customer_Email;
			}
			set
			{
				if ((this._Customer_Email != value))
				{
					this.OnCustomer_EmailChanging(value);
					this.SendPropertyChanging();
					this._Customer_Email = value;
					this.SendPropertyChanged("Customer_Email");
					this.OnCustomer_EmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
