//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPhoneStore.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name Get_CustomersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Customers", ReplyAction="*")]
        IPhoneStore.ServiceReference.Get_CustomersResponse Get_Customers(IPhoneStore.ServiceReference.Get_CustomersRequest request);
        
        // CODEGEN: Generating message contract since element name Get_StocklistResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Stocklist", ReplyAction="*")]
        IPhoneStore.ServiceReference.Get_StocklistResponse Get_Stocklist(IPhoneStore.ServiceReference.Get_StocklistRequest request);
        
        // CODEGEN: Generating message contract since element name customer_id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Orders_By_CustomerID", ReplyAction="*")]
        IPhoneStore.ServiceReference.Get_Orders_By_CustomerIDResponse Get_Orders_By_CustomerID(IPhoneStore.ServiceReference.Get_Orders_By_CustomerIDRequest request);
        
        // CODEGEN: Generating message contract since element name first_name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Customer", ReplyAction="*")]
        IPhoneStore.ServiceReference.Add_CustomerResponse Add_Customer(IPhoneStore.ServiceReference.Add_CustomerRequest request);
        
        // CODEGEN: Generating message contract since element name item_id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Item", ReplyAction="*")]
        IPhoneStore.ServiceReference.Add_ItemResponse Add_Item(IPhoneStore.ServiceReference.Add_ItemRequest request);
        
        // CODEGEN: Generating message contract since element name customer_id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Order_Item", ReplyAction="*")]
        IPhoneStore.ServiceReference.Order_ItemResponse Order_Item(IPhoneStore.ServiceReference.Order_ItemRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Check_Email_Existence", ReplyAction="*")]
        IPhoneStore.ServiceReference.Check_Email_ExistenceResponse Check_Email_Existence(IPhoneStore.ServiceReference.Check_Email_ExistenceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_CustomersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_Customers", Namespace="http://tempuri.org/", Order=0)]
        public IPhoneStore.ServiceReference.Get_CustomersRequestBody Body;
        
        public Get_CustomersRequest() {
        }
        
        public Get_CustomersRequest(IPhoneStore.ServiceReference.Get_CustomersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Get_CustomersRequestBody {
        
        public Get_CustomersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_CustomersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_CustomersResponse", Namespace="http://tempuri.org/", Order=0)]
        public IPhoneStore.ServiceReference.Get_CustomersResponseBody Body;
        
        public Get_CustomersResponse() {
        }
        
        public Get_CustomersResponse(IPhoneStore.ServiceReference.Get_CustomersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_CustomersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Get_CustomersResult;
        
        public Get_CustomersResponseBody() {
        }
        
        public Get_CustomersResponseBody(string Get_CustomersResult) {
            this.Get_CustomersResult = Get_CustomersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_StocklistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_Stocklist", Namespace="http://tempuri.org/", Order=0)]
        public IPhoneStore.ServiceReference.Get_StocklistRequestBody Body;
        
        public Get_StocklistRequest() {
        }
        
        public Get_StocklistRequest(IPhoneStore.ServiceReference.Get_StocklistRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Get_StocklistRequestBody {
        
        public Get_StocklistRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_StocklistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_StocklistResponse", Namespace="http://tempuri.org/", Order=0)]
        public IPhoneStore.ServiceReference.Get_StocklistResponseBody Body;
        
        public Get_StocklistResponse() {
        }
        
        public Get_StocklistResponse(IPhoneStore.ServiceReference.Get_StocklistResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_StocklistResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Get_StocklistResult;
        
        public Get_StocklistResponseBody() {
        }
        
        public Get_StocklistResponseBody(string Get_StocklistResult) {
            this.Get_StocklistResult = Get_StocklistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_Orders_By_CustomerIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_Orders_By_CustomerID", Namespace="http://tempuri.org/", Order=0)]
        public IPhoneStore.ServiceReference.Get_Orders_By_CustomerIDRequestBody Body;
        
        public Get_Orders_By_CustomerIDRequest() {
        }
        
        public Get_Orders_By_CustomerIDRequest(IPhoneStore.ServiceReference.Get_Orders_By_CustomerIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_Orders_By_CustomerIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string customer_id;
        
        public Get_Orders_By_CustomerIDRequestBody() {
        }
        
        public Get_Orders_By_CustomerIDRequestBody(string customer_id) {
            this.customer_id = customer_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_Orders_By_CustomerIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_Orders_By_CustomerIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public IPhoneStore.ServiceReference.Get_Orders_By_CustomerIDResponseBody Body;
        
        public Get_Orders_By_CustomerIDResponse() {
        }
        
        public Get_Orders_By_CustomerIDResponse(IPhoneStore.ServiceReference.Get_Orders_By_CustomerIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_Orders_By_CustomerIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Get_Orders_By_CustomerIDResult;
        
        public Get_Orders_By_CustomerIDResponseBody() {
        }
        
        public Get_Orders_By_CustomerIDResponseBody(string Get_Orders_By_CustomerIDResult) {
            this.Get_Orders_By_CustomerIDResult = Get_Orders_By_CustomerIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_CustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_Customer", Namespace="http://tempuri.org/", Order=0)]
        public IPhoneStore.ServiceReference.Add_CustomerRequestBody Body;
        
        public Add_CustomerRequest() {
        }
        
        public Add_CustomerRequest(IPhoneStore.ServiceReference.Add_CustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_CustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string first_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string last_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string email;
        
        public Add_CustomerRequestBody() {
        }
        
        public Add_CustomerRequestBody(string first_name, string last_name, string phone, string address, string email) {
            this.first_name = first_name;
            this.last_name = last_name;
            this.phone = phone;
            this.address = address;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_CustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_CustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public IPhoneStore.ServiceReference.Add_CustomerResponseBody Body;
        
        public Add_CustomerResponse() {
        }
        
        public Add_CustomerResponse(IPhoneStore.ServiceReference.Add_CustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_CustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Add_CustomerResult;
        
        public Add_CustomerResponseBody() {
        }
        
        public Add_CustomerResponseBody(string Add_CustomerResult) {
            this.Add_CustomerResult = Add_CustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_ItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_Item", Namespace="http://tempuri.org/", Order=0)]
        public IPhoneStore.ServiceReference.Add_ItemRequestBody Body;
        
        public Add_ItemRequest() {
        }
        
        public Add_ItemRequest(IPhoneStore.ServiceReference.Add_ItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_ItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string item_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string color;
        
        public Add_ItemRequestBody() {
        }
        
        public Add_ItemRequestBody(string item_id, string color) {
            this.item_id = item_id;
            this.color = color;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_ItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_ItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public IPhoneStore.ServiceReference.Add_ItemResponseBody Body;
        
        public Add_ItemResponse() {
        }
        
        public Add_ItemResponse(IPhoneStore.ServiceReference.Add_ItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_ItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Add_ItemResult;
        
        public Add_ItemResponseBody() {
        }
        
        public Add_ItemResponseBody(string Add_ItemResult) {
            this.Add_ItemResult = Add_ItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Order_ItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Order_Item", Namespace="http://tempuri.org/", Order=0)]
        public IPhoneStore.ServiceReference.Order_ItemRequestBody Body;
        
        public Order_ItemRequest() {
        }
        
        public Order_ItemRequest(IPhoneStore.ServiceReference.Order_ItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Order_ItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string customer_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string item_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string item_color;
        
        public Order_ItemRequestBody() {
        }
        
        public Order_ItemRequestBody(string customer_id, string item_id, string item_color) {
            this.customer_id = customer_id;
            this.item_id = item_id;
            this.item_color = item_color;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Order_ItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Order_ItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public IPhoneStore.ServiceReference.Order_ItemResponseBody Body;
        
        public Order_ItemResponse() {
        }
        
        public Order_ItemResponse(IPhoneStore.ServiceReference.Order_ItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Order_ItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Order_ItemResult;
        
        public Order_ItemResponseBody() {
        }
        
        public Order_ItemResponseBody(string Order_ItemResult) {
            this.Order_ItemResult = Order_ItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Check_Email_ExistenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Check_Email_Existence", Namespace="http://tempuri.org/", Order=0)]
        public IPhoneStore.ServiceReference.Check_Email_ExistenceRequestBody Body;
        
        public Check_Email_ExistenceRequest() {
        }
        
        public Check_Email_ExistenceRequest(IPhoneStore.ServiceReference.Check_Email_ExistenceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Check_Email_ExistenceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public Check_Email_ExistenceRequestBody() {
        }
        
        public Check_Email_ExistenceRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Check_Email_ExistenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Check_Email_ExistenceResponse", Namespace="http://tempuri.org/", Order=0)]
        public IPhoneStore.ServiceReference.Check_Email_ExistenceResponseBody Body;
        
        public Check_Email_ExistenceResponse() {
        }
        
        public Check_Email_ExistenceResponse(IPhoneStore.ServiceReference.Check_Email_ExistenceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Check_Email_ExistenceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Check_Email_ExistenceResult;
        
        public Check_Email_ExistenceResponseBody() {
        }
        
        public Check_Email_ExistenceResponseBody(string Check_Email_ExistenceResult) {
            this.Check_Email_ExistenceResult = Check_Email_ExistenceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : IPhoneStore.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<IPhoneStore.ServiceReference.WebServiceSoap>, IPhoneStore.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IPhoneStore.ServiceReference.Get_CustomersResponse IPhoneStore.ServiceReference.WebServiceSoap.Get_Customers(IPhoneStore.ServiceReference.Get_CustomersRequest request) {
            return base.Channel.Get_Customers(request);
        }
        
        public string Get_Customers() {
            IPhoneStore.ServiceReference.Get_CustomersRequest inValue = new IPhoneStore.ServiceReference.Get_CustomersRequest();
            inValue.Body = new IPhoneStore.ServiceReference.Get_CustomersRequestBody();
            IPhoneStore.ServiceReference.Get_CustomersResponse retVal = ((IPhoneStore.ServiceReference.WebServiceSoap)(this)).Get_Customers(inValue);
            return retVal.Body.Get_CustomersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IPhoneStore.ServiceReference.Get_StocklistResponse IPhoneStore.ServiceReference.WebServiceSoap.Get_Stocklist(IPhoneStore.ServiceReference.Get_StocklistRequest request) {
            return base.Channel.Get_Stocklist(request);
        }
        
        public string Get_Stocklist() {
            IPhoneStore.ServiceReference.Get_StocklistRequest inValue = new IPhoneStore.ServiceReference.Get_StocklistRequest();
            inValue.Body = new IPhoneStore.ServiceReference.Get_StocklistRequestBody();
            IPhoneStore.ServiceReference.Get_StocklistResponse retVal = ((IPhoneStore.ServiceReference.WebServiceSoap)(this)).Get_Stocklist(inValue);
            return retVal.Body.Get_StocklistResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IPhoneStore.ServiceReference.Get_Orders_By_CustomerIDResponse IPhoneStore.ServiceReference.WebServiceSoap.Get_Orders_By_CustomerID(IPhoneStore.ServiceReference.Get_Orders_By_CustomerIDRequest request) {
            return base.Channel.Get_Orders_By_CustomerID(request);
        }
        
        public string Get_Orders_By_CustomerID(string customer_id) {
            IPhoneStore.ServiceReference.Get_Orders_By_CustomerIDRequest inValue = new IPhoneStore.ServiceReference.Get_Orders_By_CustomerIDRequest();
            inValue.Body = new IPhoneStore.ServiceReference.Get_Orders_By_CustomerIDRequestBody();
            inValue.Body.customer_id = customer_id;
            IPhoneStore.ServiceReference.Get_Orders_By_CustomerIDResponse retVal = ((IPhoneStore.ServiceReference.WebServiceSoap)(this)).Get_Orders_By_CustomerID(inValue);
            return retVal.Body.Get_Orders_By_CustomerIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IPhoneStore.ServiceReference.Add_CustomerResponse IPhoneStore.ServiceReference.WebServiceSoap.Add_Customer(IPhoneStore.ServiceReference.Add_CustomerRequest request) {
            return base.Channel.Add_Customer(request);
        }
        
        public string Add_Customer(string first_name, string last_name, string phone, string address, string email) {
            IPhoneStore.ServiceReference.Add_CustomerRequest inValue = new IPhoneStore.ServiceReference.Add_CustomerRequest();
            inValue.Body = new IPhoneStore.ServiceReference.Add_CustomerRequestBody();
            inValue.Body.first_name = first_name;
            inValue.Body.last_name = last_name;
            inValue.Body.phone = phone;
            inValue.Body.address = address;
            inValue.Body.email = email;
            IPhoneStore.ServiceReference.Add_CustomerResponse retVal = ((IPhoneStore.ServiceReference.WebServiceSoap)(this)).Add_Customer(inValue);
            return retVal.Body.Add_CustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IPhoneStore.ServiceReference.Add_ItemResponse IPhoneStore.ServiceReference.WebServiceSoap.Add_Item(IPhoneStore.ServiceReference.Add_ItemRequest request) {
            return base.Channel.Add_Item(request);
        }
        
        public string Add_Item(string item_id, string color) {
            IPhoneStore.ServiceReference.Add_ItemRequest inValue = new IPhoneStore.ServiceReference.Add_ItemRequest();
            inValue.Body = new IPhoneStore.ServiceReference.Add_ItemRequestBody();
            inValue.Body.item_id = item_id;
            inValue.Body.color = color;
            IPhoneStore.ServiceReference.Add_ItemResponse retVal = ((IPhoneStore.ServiceReference.WebServiceSoap)(this)).Add_Item(inValue);
            return retVal.Body.Add_ItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IPhoneStore.ServiceReference.Order_ItemResponse IPhoneStore.ServiceReference.WebServiceSoap.Order_Item(IPhoneStore.ServiceReference.Order_ItemRequest request) {
            return base.Channel.Order_Item(request);
        }
        
        public string Order_Item(string customer_id, string item_id, string item_color) {
            IPhoneStore.ServiceReference.Order_ItemRequest inValue = new IPhoneStore.ServiceReference.Order_ItemRequest();
            inValue.Body = new IPhoneStore.ServiceReference.Order_ItemRequestBody();
            inValue.Body.customer_id = customer_id;
            inValue.Body.item_id = item_id;
            inValue.Body.item_color = item_color;
            IPhoneStore.ServiceReference.Order_ItemResponse retVal = ((IPhoneStore.ServiceReference.WebServiceSoap)(this)).Order_Item(inValue);
            return retVal.Body.Order_ItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IPhoneStore.ServiceReference.Check_Email_ExistenceResponse IPhoneStore.ServiceReference.WebServiceSoap.Check_Email_Existence(IPhoneStore.ServiceReference.Check_Email_ExistenceRequest request) {
            return base.Channel.Check_Email_Existence(request);
        }
        
        public string Check_Email_Existence(string email) {
            IPhoneStore.ServiceReference.Check_Email_ExistenceRequest inValue = new IPhoneStore.ServiceReference.Check_Email_ExistenceRequest();
            inValue.Body = new IPhoneStore.ServiceReference.Check_Email_ExistenceRequestBody();
            inValue.Body.email = email;
            IPhoneStore.ServiceReference.Check_Email_ExistenceResponse retVal = ((IPhoneStore.ServiceReference.WebServiceSoap)(this)).Check_Email_Existence(inValue);
            return retVal.Body.Check_Email_ExistenceResult;
        }
    }
}
